---
# tasks file for add-local-user

- name: "add_local_user | Add a user"
  vars:
    add_local_user_random_password: "{{ lookup('password', '/dev/null length=40 chars=ascii_letters')
                                          |password_hash('sha512') }}"
  ansible.builtin.user:
    name: "{{ add_local_user_user['name'] }}"
    comment: "{{ add_local_user_user['comment']|default('') }}"
    password: "{{ add_local_user_user['password']|default(add_local_user_random_password) }}"
    shell: "{{ add_local_user_user['shell']|default(add_local_user_default_shell) }}"
    system: "{{ add_local_user_user['system']|default(add_local_user_system_user) }}"
    update_password: "{{ add_local_user_user['update_password_policy']
                           |default(add_local_user_default_password_policy) }}"
    groups:
      - "sudo"
    state: "{{ add_local_user_user['state']|default('present') }}"
  tags:
    - "add_local_user"
    - "add_local_user_user"
    - "add_local_user_user_create_user"

- name: "add_local_user | Allow sudo without password, when no password is given"
  ansible.builtin.lineinfile:
    path: "/etc/sudoers"
    line: "{{ add_local_user_user['name'] }} ALL=(ALL) NOPASSWD: ALL"
  when: "add_local_user_user['password'] is not defined"

- name: "add_local_user | Install authorized_key for that user (key string)"
  ansible.posix.authorized_key:
    user: "{{ add_local_user_user['name'] }}"
    key: "{{ add_local_user_user['sshkey'] }}"
    manage_dir: true
  when: "'sshkey' in add_local_user_user and add_local_user_user['state']|default('present') == 'present'"
  tags:
    - "add_local_user"
    - "add_local_user_user"
    - "add_local_user_user_deployment_key"

- name: "add_local_user | Install authorized_key for that user (key file)"
  ansible.posix.authorized_key:
    user: "{{ add_local_user_user['name'] }}"
    key: "{{ lookup('file', add_local_user_user['sshkey_file']) }}"
    path: "/home/{{ add_local_user_user['name'] }}/.ssh/authorized_keys"
    manage_dir: true
    state: "{{ add_local_user_user['state']|default('present') }}"
  when:
    - "'sshkey_file' in add_local_user_user"
    - "'sshkey' not in add_local_user_user"
    - "add_local_user_user['state']|default('present') == 'present'"
  tags:
    - "add_local_user"
    - "add_local_user_user"
    - "add_local_user_user_deployment_key"

- name: "add_local_user | Allow user to log in (UCR)"
  univention.ucs_modules.univention_config_registry:
    kvlist:
      - key: "auth/sshd/user/{{ add_local_user_user['name'] }}"
        value: "yes"
    state: "{{ add_local_user_user['state']|default('present') }}"
  tags:
    - "add_local_user"
    - "add_local_user_user"
    - "add_local_user_user_allow_login"

...
