---

- name: "disable_ipv6 | Disable IPv6 with sysctl"
  ansible.posix.sysctl:
    name: "{{ disable_ipv6_item }}"
    value: "1"
    state: "present"
    reload: true
  loop:
    - "net.ipv6.conf.default.disable_ipv6"
    - "net.ipv6.conf.all.disable_ipv6"
    - "net.ipv6.conf.lo.disable_ipv6"
  loop_control:
    loop_var: "disable_ipv6_item"
  tags:
    - "disable_ipv6"
    - "disable_ipv6_sysctl"

- name: "disable_ipv6 | Blacklist IPv6 in modprobe"
  ansible.builtin.lineinfile:
    line: "blacklist ipv6"
    dest: "/etc/modprobe.d/blacklist.conf"
    mode: "0644"
    create: true
  tags:
    - "disable_ipv6"
    - "disable_ipv6_modprobe"

...
