---

- name: "ldapsearch_user | Create LDAPSearch user"
  block:
    - name: "ldapsearch_user | Create LDAPSearch user"
      ansible.builtin.command: >
        udm users/ldap create
          --position "cn=users,{{ ldapsearch_user_basedn }}"
          --set name="{{ ldapsearch_user_item.name | default(ldapsearch_user_item.username) }}"
          --set username="{{ ldapsearch_user_item.username }}"
          --set lastname="{{ ldapsearch_user_item.lastname | default(ldapsearch_user_item.username) }}"
          --set password="{{ ldapsearch_user_item.password }}"
          --ignore_exists
      changed_when: "ldapsearch_user_create_result.stdout is not search('Object exists')"
      loop: "{{ ldapsearch_user_list }}"
      loop_control:
        loop_var: "ldapsearch_user_item"
      no_log: "{{ ldapsearch_user_hide_logging | default(true) | bool }}"
      register: "ldapsearch_user_create_result"
      tags:
        - "ldapsearch_user_create"

    - name: "ldapsearch_user | Update LDAPSearch user"
      ansible.builtin.command: >
        udm users/ldap modify
          --dn "uid={{ ldapsearch_user_item.name | default(ldapsearch_user_item.username) }},cn=users,{{
                          ldapsearch_user_basedn }}"
          --set username="{{ ldapsearch_user_item.username }}"
          --set lastname="{{ ldapsearch_user_item.lastname | default(ldapsearch_user_item.username) }}"
      changed_when: "ldapsearch_user_update_result.stdout is not search('No modification')"
      loop: "{{ ldapsearch_user_list }}"
      loop_control:
        loop_var: "ldapsearch_user_item"
      no_log: "{{ ldapsearch_user_hide_logging | default(true) | bool }}"
      register: "ldapsearch_user_update_result"
      tags:
        - "ldapsearch_user_update"

    - name: "ldapsearch_user | Update LDAPSearch user password"
      ansible.builtin.command: >
        udm users/ldap modify
          --dn "uid={{ ldapsearch_user_item.name | default(ldapsearch_user_item.username) }},cn=users,{{
                          ldapsearch_user_basedn }}"
          --set password="{{ ldapsearch_user_item.password }}"
      changed_when: "ldapsearch_user_update_password_result.stdout is search('Object modified:')"
      failed_when:
        - "ldapsearch_user_update_password_result.rc > 0"
        - "ldapsearch_user_update_password_result is not search('Password has been used before.')"
      loop: "{{ ldapsearch_user_list }}"
      loop_control:
        loop_var: "ldapsearch_user_item"
      no_log: "{{ ldapsearch_user_hide_logging | default(true) | bool }}"
      register: "ldapsearch_user_update_password_result"
      tags:
        - "ldapsearch_user_update_password"

    - name: "ldapsearch_user | Create LDAPSearch user (per Tenant)"
      ansible.builtin.command: >
        udm users/ldap create
          --position "{{ ldapsearch_user_item.tenant_ou }},{{ ldapsearch_user_basedn }}"
          --set name="{{ ldapsearch_user_item.name | default(ldapsearch_user_item.username) }}"
          --set username="{{ ldapsearch_user_item.username }}"
          --set lastname="{{ ldapsearch_user_item.lastname | default(ldapsearch_user_item.username) }}"
          --set password="{{ ldapsearch_user_item.password }}"
          --ignore_exists
      changed_when: "ldapsearch_user_create_tenantbased_result.stdout is not search('Object exists')"
      loop: "{{ ldapsearch_user_list_tenantbased }}"
      loop_control:
        loop_var: "ldapsearch_user_item"
      no_log: "{{ ldapsearch_user_hide_logging | default(true) | bool }}"
      register: "ldapsearch_user_create_tenantbased_result"
      tags:
        - "ldapsearch_user_create_tenantbased"

    - name: "ldapsearch_user | Update LDAPSearch user (per Tenant)"
      ansible.builtin.command: >
        udm users/ldap modify
          --dn "uid={{ ldapsearch_user_item.name | default(ldapsearch_user_item.username) }},{{
                        ldapsearch_user_item.tenant_ou }},{{ ldapsearch_user_basedn }}"
          --set username="{{ ldapsearch_user_item.username }}"
          --set lastname="{{ ldapsearch_user_item.lastname | default(ldapsearch_user_item.username) }}"
      changed_when: "ldapsearch_user_update_tenantbased_result.stdout is not search('No modification')"
      loop: "{{ ldapsearch_user_list_tenantbased }}"
      loop_control:
        loop_var: "ldapsearch_user_item"
      no_log: "{{ ldapsearch_user_hide_logging | default(true) | bool }}"
      register: "ldapsearch_user_update_tenantbased_result"
      tags:
        - "ldapsearch_user_update_tenantbased"

    - name: "ldapsearch_user | Update LDAPSearch user password (per Tenant)"
      ansible.builtin.command: >
        udm users/ldap modify
          --dn "uid={{ ldapsearch_user_item.name | default(ldapsearch_user_item.username) }},{{
                        ldapsearch_user_item.tenant_ou }},{{ ldapsearch_user_basedn }}"
          --set password="{{ ldapsearch_user_item.password }}"
      changed_when: "ldapsearch_user_update_password_tenantbased_result.stdout is search('Object modified:')"
      failed_when:
        - "ldapsearch_user_update_password_tenantbased_result.rc > 0"
        - "ldapsearch_user_update_password_tenantbased_result is not search('Password has been used before.')"
      loop: "{{ ldapsearch_user_list_tenantbased }}"
      loop_control:
        loop_var: "ldapsearch_user_item"
      no_log: "{{ ldapsearch_user_hide_logging | default(true) | bool }}"
      register: "ldapsearch_user_update_password_tenantbased_result"
      tags:
        - "ldapsearch_user_update_password"

  when: "ldapsearch_user_server_type | default('master') != 'backup'"
  tags:
    - "ldapsearch_user"

...
