include:
  - project: 'univention/customers/dataport/deployment/ci-tooling'
    ref: main
    file: '.gitlab-ci-ansible.yml'

stages:
  - .pre
  - prepare
  - release
  - publish

publish:
  artifacts:
    paths:
      - univention-ucs_roles-*
    expire_in: 14 days
  before_script:
    - sed -i "/version. [0-9]\.[0-9]\.[0-9]/s/[0-9]\.[0-9]\.[0-9]/$RELEASE_VERSION/" galaxy.yml
  image: artifacts.knut.univention.de/upx/container-tooling/automation-ansible:main
  only:
    - main
  script:
    - ansible-galaxy collection build
    - ansible-galaxy collection publish --api-key ${ANSIBLE_GALAXY_API_KEY} univention-ucs_roles-${RELEASE_VERSION}.tar.gz
  stage: publish
  variables:
    GIT_DEPTH: "1"