---

# reference: https://pre-commit.com

repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v6.0.0"
    hooks:
      - id: "check-added-large-files"
      - id: "check-case-conflict"
      - id: "check-docstring-first"
      - id: "check-executables-have-shebangs"
      - id: "check-json"
      - id: "check-symlinks"
      - id: "detect-private-key"
      - id: "end-of-file-fixer"
      - id: "trailing-whitespace"

  - repo: "https://github.com/adrienverge/yamllint"
    rev: "v1.38.0"
    hooks:
      - id: "yamllint"
        args:
          - "-c=.yamllint"

  # - repo: "https://github.com/ansible/ansible-lint"
  #   rev: "v26.4.0"
  #   hooks:
  #     - id: "ansible-lint"

  - repo: "https://github.com/PyCQA/flake8"
    rev: "7.3.0"
    hooks:
      - id: "flake8"

  - repo: "local"
    hooks:
      - id: "generate-readme"
        name: "Generate README"
        entry: "scripts/generate_readme.py"
        language: "python"
        types: ["file"]
        always_run: true
        pass_filenames: false

      - id: "add-readme"
        name: "Add README.md to Git index"
        entry: "git add README.md"
        language: "system"
        always_run: true
        pass_filenames: false
...
