---

add_local_user_user:
  name: "ansible"
  comment: "ansible user"
  password: "{{ 'ansible' | password_hash('sha512') }}"

add_local_user_default_shell: "/bin/bash"
add_local_user_default_password_policy: "on_create"
add_local_user_system_user: true

...
