---
- name: "Converge"
  hosts: "all"
  pre_tasks:
    - name: "Get LDAP base DN from UCR"
      ansible.builtin.command: "ucr get ldap/base"
      register: "portal_configure_title_ucr_ldap_base"
      changed_when: false
  roles:
    - role: "univention.ucs_roles.portal_configure_title"
      vars:
        portal_configure_title_basedn: "{{ portal_configure_title_ucr_ldap_base.stdout }}"
        portal_configure_title_titles: []
