---
- name: "univention_install | Clean apt package cache"
  ansible.builtin.command:
    cmd: "apt clean"
  changed_when: false
  when: "univention_install_clear_apt_cache | bool"
  tags:
    - "univention_install"
    - "univention_install_clean_package_cache"

- name: "univention_install | Install via univention-install"
  ansible.builtin.command:
    cmd: "univention-install --yes {{ univention_install_name }}"
  changed_when: "univention_install_result.stdout is not search('is already the newest version')"
  check_mode: false
  delay: 10
  register: "univention_install_result"
  retries: 10
  until: "univention_install_result.rc == 0"
  tags:
    - "univention_install"
    - "univention_install_run"
