---

- name: "dovecot_connector | Install DC connector"
  block:
    - name: "Assert variables"
      ansible.builtin.assert:
        that:
          - "dovecot_connector_basedn | length > 0"
          - "dovecot_connector_adm_password | length > 0"
          - "dovecot_connector_adm_username | length > 0"
          - "dovecot_connector_domain_name | length > 0"

    - name: "dovecot_connector | Create DNS Alias"
      ansible.builtin.command: |
        udm dns/alias create
          --superordinate "zoneName={{ dovecot_connector_domain_name }},cn=dns,{{ dovecot_connector_basedn }}"
          --set name={{ dovecot_connector_soap_prefix }}
          --set cname={{ dovecot_connector_domain_prefix }}
          --ignore_exists
      changed_when: "dovecot_connector_dns_alias.stdout is search('Object created')"
      failed_when:
        - "dovecot_connector_dns_alias.rc > 0"
        - "'already in use' not in dovecot_connector_dns_alias.stdout"
      register: "dovecot_connector_dns_alias"
      when: "dovecot_connector_domain_prefix | default('') | length > 0"
      tags:
        - "dovecot_connector_dns_alias"

    - name: "dovecot_connector | Install dovecot-connector"
      vars:
        install_packages_app_version_map: "{{ dovecot_connector_app_version_map }}"
        install_packages_temp_pw_file: "{{ dovecot_connector_temp_pw_file }}"
        install_packages_install_apps:
          - "dovecot-connector"
        install_packages_additional_options: >
          DCC_ADM_ACCEPTED_EXIT_CODES="{{ dovecot_connector_adm_accepted_exit_codes }}"
          DCC_ADM_HOST="{{ dovecot_connector_adm_host }}"
          DCC_ADM_PORT="{{ dovecot_connector_adm_port }}"
          DCC_ADM_USERNAME="{{ dovecot_connector_adm_username }}"
          DCC_ADM_PASSWORD="{{ dovecot_connector_adm_password }}"
          DCC_ADM_URI="{{ dovecot_connector_adm_uri }}"
          DCC_DC_VMAIL_TEMPLATE="{{ dovecot_connector_dc_vmail_template }}"
          DCC_LOGLEVEL="{{ dovecot_connector_loglevel }}"

      ansible.builtin.include_role:
        name: "install_packages"
      no_log: "{{ dovecot_connector_hide_logging }}"
      tags:
        - "dovecot_connector_install"

    - name: "dovecot_connector | Get current settings"
      ansible.builtin.command:
        cmd: "univention-app configure dovecot-connector --list"
      changed_when: false
      register: "dovecot_connector_get_current_settings_result"
      tags:
        - "dovecot_connector_get_current_settings"

    - name: "dovecot_connector | Check if settings are still correct"
      vars:
        dovecot_connector_settings_correct: true
      ansible.builtin.set_fact:
        dovecot_connector_settings_correct: "{{ dovecot_connector_settings_correct
          if (dovecot_connector_get_current_settings_result.stdout is search(dovecot_connector_config_item))
          else false }}"
      loop:
        - "DCC_ADM_ACCEPTED_EXIT_CODES: '{{ dovecot_connector_adm_accepted_exit_codes }}'"
        - "DCC_ADM_HOST: '{{ dovecot_connector_adm_host }}'"
        - "DCC_ADM_PORT: {{ dovecot_connector_adm_port }}"
        - "DCC_ADM_USERNAME: '{{ dovecot_connector_adm_username }}'"
        - "DCC_ADM_PASSWORD: '{{ dovecot_connector_adm_password }}'"
        - "DCC_ADM_URI: '{{ dovecot_connector_adm_uri }}'"
        - "DCC_DC_VMAIL_TEMPLATE: '{{ dovecot_connector_dc_vmail_template }}'"
        - "DCC_LOGLEVEL: '{{ dovecot_connector_loglevel }}'"
      loop_control:
        loop_var: "dovecot_connector_config_item"
      no_log: "{{ dovecot_connector_hide_logging }}"
      tags:
        - "dovecot_connector_check_settings"

    - name: "dovecot_connector | Configure settings"
      ansible.builtin.command:
        cmd: >
          univention-app configure dovecot-connector --set
          DCC_ADM_ACCEPTED_EXIT_CODES="{{ dovecot_connector_adm_accepted_exit_codes }}"
          DCC_ADM_HOST="{{ dovecot_connector_adm_host }}"
          DCC_ADM_PORT="{{ dovecot_connector_adm_port }}"
          DCC_ADM_USERNAME="{{ dovecot_connector_adm_username }}"
          DCC_ADM_PASSWORD="{{ dovecot_connector_adm_password }}"
          DCC_ADM_URI="{{ dovecot_connector_adm_uri }}"
          DCC_DC_VMAIL_TEMPLATE="{{ dovecot_connector_dc_vmail_template }}"
          DCC_LOGLEVEL="{{ dovecot_connector_loglevel }}"

      no_log: "{{ dovecot_connector_hide_logging }}"
      when: "not dovecot_connector_settings_correct"
      tags:
        - "dovecot_connector_configure"
  when: "dovecot_connector_server_type | default('master') != 'backup'"
  tags:
    - "dovecot_connector"

...
