---

- name: "Verify"
  hosts: "all"
  tasks:
    - name: "Check IPv6 disabled for all interfaces"
      ansible.builtin.command: "sysctl net.ipv6.conf.all.disable_ipv6"
      register: "disable_ipv6_sysctl"
      changed_when: false
    - name: "Assert IPv6 is disabled"
      ansible.builtin.assert:
        that: "' = 1' in disable_ipv6_sysctl.stdout"
