---

- name: "Converge"
  hosts: "all"
  tasks:
    - name: "Get LDAP base DN from UCR"
      ansible.builtin.command: "ucr get ldap/base"
      register: "ucr_ldap_base"
      changed_when: false
    - name: "Get domain name from UCR"
      ansible.builtin.command: "ucr get domainname"
      register: "ucr_domain_name"
      changed_when: false
  roles:
    - role: "univention.ucs_roles.configure_saml_single_server"
      vars:
        configure_saml_single_server_basedn: "{{ ucr_ldap_base.stdout }}"
        configure_saml_single_server_domain_name: "{{ ucr_domain_name.stdout }}"
        configure_saml_single_server_external_hostname: "primary.{{ ucr_domain_name.stdout }}"
        configure_saml_single_server_type: "master"
