#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright 2018 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

import univention.config_registry
import os
import subprocess

EXPORTER_DIR = '/var/lib/prometheus/node-exporter'
DATA_DIR = '/var/lib/univention-appcenter/apps/prometheus/data/data'

if __name__ == '__main__':

    ucr = univention.config_registry.ConfigRegistry()
    ucr.load()
    data = list()

    try:
        out = subprocess.check_output(['du', '-xsb0', DATA_DIR])
        size = out.split()[0]
    except Exception:
        size = '0'
    data.append('prometheus_data_directory_size_bytes{directory="%s"} %s' % (DATA_DIR, size))

    tmp_filename = os.path.join(EXPORTER_DIR, 'ucs-prometheus-info.%s' % os.getpid())
    filename = os.path.join(EXPORTER_DIR, 'ucs-prometheus-info.prom')
    with open(tmp_filename, 'wb') as f:
        for d in data:
            f.write(d + '\n')
    if os.path.exists(tmp_filename):
        os.rename(tmp_filename, filename)
