---

- name: "univention_prune_kernels | check for purging kernels"
  ansible.builtin.command: "univention-prune-kernels --dry-run --verbose"
  register: "univention_prune_kernels_check"
  tags:
    - "univention_prune_kernels"
    - "univention_prune_kernels_check"

- name: "univention_prune_kernels | do it"
  ansible.builtin.command: "univention-prune-kernels --verbose"
  when:
    - "univention_prune_kernels_check.stdout is search('Purging kernel package:')"
    - "univention_prune_kernels_check.rc == 0"
  tags:
    - "univention_prune_kernels"
    - "univention_prune_kernels_do_it"

...
