---

- name: "configure_error_detail_show | Enable or disable http show tracebacks"
  univention.ucs_modules.univention_config_registry:
    keys:
      umc/http/show_tracebacks: "{{ configure_error_detail_show_http_tracebacks }}"
  tags:
    - "configure_error_detail_show"

- name: "configure_error_detail_show | Enable or disable directory manager rest show tracebacks"
  univention.ucs_modules.univention_config_registry:
    keys:
      directory/manager/rest/show-tracebacks: "{{ configure_error_detail_show_directory_manager_rest_tracebacks }}"
  tags:
    - "configure_error_detail_show"

- name: "configure_error_detail_show | Enable or disable SAML IDP show errors"
  univention.ucs_modules.univention_config_registry:
    keys:
      saml/idp/show-errors: "{{ configure_error_detail_show_saml_idp_errors }}"
  tags:
    - "configure_error_detail_show"

- name: "configure_error_detail_show | Enable or disable SAML IDP show reporting errors"
  univention.ucs_modules.univention_config_registry:
    keys:
      saml/idp/show-error-reporting: "{{ configure_error_detail_show_saml_idp_error_reporting }}"
  tags:
    - "configure_error_detail_show"

...
