---

- name: "Converge"
  hosts: "all"
  tasks:
    - name: "Get LDAP base DN from UCR"
      ansible.builtin.command: "ucr get ldap/base"
      register: "ucr_ldap_base"
      changed_when: false
  roles:
    - role: "univention.ucs_roles.configure_password_policies"
      vars:
        configure_password_policies_dn: "cn=default-settings,cn=pwhistory,cn=auth,cn=univention,{{ ucr_ldap_base.stdout }}"
