---

- name: "cleanup_portal | Install Dashboard"
  block:
    - name: "Allow Domain Admin group access to dashboard features"
      # exit codes
      #  0: on "Object modified: <dn>" and "No modification: <dn>"
      #  3: on "E: object not found"
      ansible.builtin.command:
        argv:
          - "udm"
          - "portals/entry"
          - "modify"
          - "--dn"
          - "{{ cleanup_portal_item }}"
          - "--set"
          - "allowedGroups={{ cleanup_portal_domain_admin_group }}"
      loop:
        - "{{ cleanup_portal_prometheus_dn }}"
        - "{{ cleanup_portal_admin_dashboard_dn }}"
      loop_control:
        loop_var: "cleanup_portal_item"
      register: "cleanup_portal_output1"
      changed_when: "cleanup_portal_output1 | regex_search('Object modified: cn=')"
      tags:
        - "cleanup_portal_domain_admin_permissions"

    - name: "cleanup_portal | Add portal entries to Administration category"
      ansible.builtin.command:
        argv:
          - "udm"
          - "portals/category"
          - "modify"
          - "--dn"
          - "cn=Administration,cn=category,{{ cleanup_portal_portal_dn }}"
          - "--append"
          - "{{ cleanup_portal_prometheus_dn }}"
          - "--append"
          - "{{ cleanup_portal_admin_dashboard_dn }}"
      register: "cleanup_portal_output2"
      changed_when: "cleanup_portal_output2 | regex_search('Object modified: cn=')"
      tags:
        - "cleanup_portal_add_portal_entries"

    - name: "cleanup_portal | Remove portal entries from domain admin category"
      ansible.builtin.command:
        argv:
          - "udm"
          - "portals/category"
          - "modify"
          - "--dn"
          - "cn=domain-admin,cn=category,{{ cleanup_portal_portal_dn }}"
          - "--remove"
          - "{{ cleanup_portal_prometheus_dn }}"
          - "--remove"
          - "{{ cleanup_portal_admin_dashboard_dn }}"
      register: "cleanup_portal_output3"
      changed_when: "cleanup_portal_output3 | regex_search('Object modified: cn=')"
      tags:
        - "cleanup_portal_remove_portal_entries"

    - name: "cleanup_portal | Deactivate portal entries"
      ansible.builtin.command:
        argv:
          - "udm"
          - "portals/entry"
          - "modify"
          - "--dn"
          - "{{ cleanup_portal_item }}"
          - "--set"
          - "activated=FALSE"
      loop:
        - "{{ cleanup_portal_prometheus_dn }}"
        - "{{ cleanup_portal_admin_dashboard_dn }}"
      loop_control:
        loop_var: "cleanup_portal_item"
      register: "cleanup_portal_output4"
      changed_when: "cleanup_portal_output4 | regex_search('Object modified: cn=')"
      tags:
        - "cleanup_portal_deactivate_portal_entries"
  when: "'dashboard' in cleanup_portal_install_services"
  tags:
    - "cleanup_portal"

...
