---

- name: "install_multitenant_acls | Enable ACL repository"
  ansible.builtin.include_role:
    name: "univention_repository_component"
  vars:
    univention_repository_component_name: "{{ install_multitenant_acls_customer_repo_name }}"
    univention_repository_component_parts: "{{ install_multitenant_acls_customer_repo_parts }}"
    univention_repository_component_prefix: "{{ install_multitenant_acls_customer_repo_prefix }}"
    univention_repository_component_server: "{{ install_multitenant_acls_customer_repo_server }}"
    univention_repository_component_username: "{{ install_multitenant_acls_customer_repo_username }}"
    univention_repository_component_password: "{{ install_multitenant_acls_customer_repo_password }}"
  tags:
    - "install_multitenant_acls"
    - "install_multitenant_acls_enable_repository"

- name: "install_multitenant_acls | Disable kerberos DNS lookup"
  univention.ucs_modules.univention_config_registry:
    keys:
      kerberos/kdc: "127.0.0.1"
      kerberos/defaults/dns_lookup_kdc: false
  tags:
    - "install_multitenant_acls"
    - "install_multitenant_acls_disable_kerberos"

- name: "install_multitenant_acls | Install Multitenat ACLs"
  block:
    - name: "install_multitenant_acls | Copy ACL template to machine"
      ansible.builtin.template:
        dest: "{{ install_multitenant_acls_json_path }}"
        src: "multitenant-acls.j2"
        mode: "744"
      changed_when: false
      no_log: "{{ install_multitenant_acls_hide_logging | default(true) | bool }}"
      tags:
        - "install_multitenant_acls_copy_acl_template"

    - name: "install_multitenant_acls | Install ACL package"
      ansible.builtin.include_role:
        name: "univention_install"
      vars:
        univention_install_name: "{{ install_multitenant_acls_package_name }}"
      tags:
        - "install_multitenant_acls_install_acl_package"

    - name: "install_multitenant_acls | Create Mandant structure"
      ansible.builtin.command:
        cmd: "/usr/share/{{ install_multitenant_acls_package_name }}/{{ install_multitenant_acls_script_name }}
              {{ install_multitenant_acls_json_path }}"
      changed_when: "install_multitenant_acls_run_structure_creation.stdout is not search('No modification')"
      register: "install_multitenant_acls_run_structure_creation"
      tags:
        - "install_multitenant_acls_run_structure_creation"

    - name: "install_multitenant_acls | Make sure template is removed"
      ansible.builtin.file:
        path: "{{ install_multitenant_acls_json_path }}"
        state: "absent"
      changed_when: false
      tags:
        - "always"
        - "install_multitenant_acls_copy_acl_template"
  when: "install_multitenant_acls_server_type | default('master') != 'backup'"
  tags:
    - "install_multitenant_acls"

- name: "install_multitenant_acls | Disable nested ACL groups"
  univention.ucs_modules.univention_config_registry:
    keys:
      ldap/acl/nestedgroups: "false"
  tags:
    - "install_multitenant_acls"
    - "install_multitenant_acls_disable_nested_acl_groups"

...
