---

galaxy_info:
  role_name: "configure_network_interface_names"
  author: "Univention"
  description: "Use old network interface names like eth0, ethX"
  company: "Univention GmbH"

  issue_tracker_url: "https://forge.univention.org"

  license: "GPL-3.0-or-later"

  min_ansible_version: "2.10"

  platforms:
    - name: "Debian"
      versions:
        - "all"

  galaxy_tags:
    - "univention"
    - "ucs"
    - "setup"

dependencies: []

...
