---
- name: "Converge"
  hosts: "all"
  tasks:
    - name: "Get LDAP base DN from UCR"
      ansible.builtin.command: "ucr get ldap/base"
      register: "cleanup_portal_ucr_ldap_base"
      changed_when: false
  roles:
    - role: "univention.ucs_roles.cleanup_portal"
      vars:
        cleanup_portal_basedn: "{{ cleanup_portal_ucr_ldap_base.stdout }}"
        cleanup_portal_install_services: []
