---

- name: "Update package list"
  ansible.builtin.include_role:
    name: "force_package_list_update"
  tags:
    - "install_apps_ox_post"
    - "install_apps_ox_post_update_packages"

- name: "Install additional SAML packages"
  ansible.builtin.command: "univention-install open-xchange-saml-ucs open-xchange-saml"
  register: "install_apps_ox_post_package_install"
  retries: 10
  delay: 10
  until: "install_apps_ox_post_package_install.rc == 0"
  tags:
    - "install_apps_ox_post"
    - "install_apps_ox_post_saml_packages"

- name: "Configure various OpenXchange aspects in UCR"
  univention.ucs_modules.univention_config_registry:
    keys:
      ox/cfg/sessiond.properties/com.openexchange.sessiond.autologin: "false"
      ox/listener/imaplogin_value: "{}*dovecotadmin"
  tags:
    - "install_apps_ox_post"
    - "install_apps_ox_post_ucr_config"

- name: "Restart the Univention Directory Listener"
  ansible.builtin.command: "/etc/init.d/univention-directory-listener restart"
  tags:
    - "install_apps_ox_post"
    - "install_apps_ox_post_restart_directory_listener"

- name: "Set OpenXchange passwordSource to 'global'"
  ansible.builtin.lineinfile:
    path: "/opt/open-xchange/etc/mail.properties"
    line: "com.openexchange.mail.passwordSource=global"
    regexp: "com\\.openexchange\\.mail\\.passwordSource=.*"
    state: "present"
  tags:
    - "install_apps_ox_post"
    - "install_apps_ox_post_password_source"

- name: "Get dovecot admin password"
  # noqa: command-instead-of-module
  ansible.builtin.command: "sed -e 's|.*{PLAIN}||;s|:.*||' /etc/dovecot/master-users"
  register: "install_apps_ox_post_dovecot_admin_password"
  no_log: true
  tags:
    - "install_apps_ox_post"
    - "install_apps_ox_post_get_admin_password"

- name: "Set Sieve master password to admin password"
  ansible.builtin.lineinfile:
    path: "/opt/open-xchange/etc/mail.properties"
    line: "com.openexchange.mail.masterPassword={{ install_apps_ox_post_dovecot_admin_password.stdout }}"
    regexp: "com\\.openexchange\\.mail\\.masterPassword=.*"
    state: "present"
  tags:
    - "install_apps_ox_post"
    - "install_apps_ox_post_set_sieve_master_password"

- name: "Add saml login to OpenXchange config"
  ansible.builtin.lineinfile:
    path: "/opt/open-xchange/etc/as-config.yml"
    line: "    samlLogin: true"
    regexp: ".*samlLogin:.*"
    insertafter: "host: all"
    state: "present"
  tags:
    - "install_apps_ox_post"
    - "install_apps_ox_post_saml_login"

- name: "Install saml.properties file"
  ansible.builtin.template:
    dest: "/opt/open-xchange/etc/saml.properties"
    src: "saml.properties.j2"
    mode: "0640"
  tags:
    - "install_apps_ox_post"
    - "install_apps_ox_post_saml_properties_file"

- name: "Configure OpenXchange as SAML service provider"
  ansible.builtin.command: >
    udm saml/serviceprovider create
    --ignore_exists
    --position "cn=saml-serviceprovider,cn=univention,{{ install_apps_ox_post_basedn }}"
    --set AssertionConsumerService="https://{{ install_apps_ox_post_external_hostname }}/appsuite/api/saml/acs"
    --set Identifier="https://{{ install_apps_ox_post_external_hostname }}/appsuite/"
    --set LDAPattributes="mailPrimaryAddress"
    --set LDAPattributes="uid"
    --set NameIDFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
    --set isActivated="TRUE"
    --set serviceProviderOrganizationName="Open-Xchange Service Provider"
    --set simplesamlAttributes="TRUE"
    --set simplesamlNameIDAttribute="uid"
  tags:
    - "install_apps_ox_post"
    - "install_apps_ox_post_ox_as_saml_provider"

- name: "Cert File operations"
  block:
    - name: "Create temporary directory for certificate operations"
      ansible.builtin.tempfile:
        state: "directory"
      register: "install_apps_ox_post_cert_temp_dir"
      tags:
        - "install_apps_ox_post_cert_temp_dir"

    - name: "Create PKCS12 file from IDP certificate"
      community.crypto.openssl_pkcs12:
        action: "export"
        path: "{{ install_apps_ox_post_cert_temp_dir.path }}/temp_output.p12"
        certificate_path: "/etc/simplesamlphp/{{ install_apps_ox_post_external_hostname }}-idp-certificate.crt"
        privatekey_path: "/etc/simplesamlphp/{{ install_apps_ox_post_external_hostname }}-idp-certificate.key"
        other_certificates: "/etc/univention/ssl/ucsCA/CAcert.pem"
        friendly_name: "{{ install_apps_ox_post_external_hostname }}"
        passphrase: "{{ install_apps_ox_post_ox_keystore_passphrase }}"
      tags:
        - "iinstall_apps_ox_post_cert_idp_certificate"

    - name: "Import PKCS12 into keystore"
      community.general.java_cert:
        pkcs12_path: "{{ install_apps_ox_post_cert_temp_dir.path }}/temp_output.p12"
        pkcs12_password: "{{ install_apps_ox_post_ox_keystore_passphrase }}"
        pkcs12_alias: "{{ install_apps_ox_post_external_hostname }}"
        keystore_create: true
        keystore_type: "JKS"
        keystore_path: "{{ install_apps_ox_post_cert_temp_dir.path }}/my-keystore.jks"
        keystore_pass: "{{ install_apps_ox_post_ox_keystore_passphrase }}"
        cert_alias: "{{ install_apps_ox_post_external_hostname }}"
        state: "present"
      tags:
        - "install_apps_ox_post_cert_idp_certificate_import"

    - name: "Export keystore into a temporary format"
      ansible.builtin.command: >
        keytool -export -alias "{{ install_apps_ox_post_external_hostname }}"
        -file "{{ install_apps_ox_post_cert_temp_dir.path }}/{{ install_apps_ox_post_external_hostname }}.cer"
        -keystore "{{ install_apps_ox_post_cert_temp_dir.path }}/my-keystore.jks"
        -deststorepass "{{ install_apps_ox_post_ox_keystore_passphrase }}"
      tags:
        - "install_apps_ox_post_cert_idp_certificate_export"

    - name: "Change the system keystore password"
      ansible.builtin.command: >
        keytool -storepasswd
        -new "{{ install_apps_ox_post_ox_keystore_passphrase }}"
        -storepass changeit
        -keystore /etc/ssl/certs/java/cacerts
      # noqa ignore-errors
      ignore_errors: true
      tags:
        - "install_apps_ox_post_cert_keystore_password"

    - name: "Use new password in jks-keystore script"
      ansible.builtin.lineinfile:
        path: "/etc/ca-certificates/update.d/jks-keystore"
        line: "storepass='{{ install_apps_ox_post_ox_keystore_passphrase }}'"
        regexp: "^storepass='.*'$"
        state: "present"
      tags:
        - "install_apps_ox_post_cert_keystore_password_jks"

    - name: "Import temporary file into system keystore"
      community.general.java_cert:
        cert_path: "{{ install_apps_ox_post_cert_temp_dir.path }}/{{ install_apps_ox_post_external_hostname }}.cer"
        cert_alias: "{{ install_apps_ox_post_external_hostname }}"
        keystore_type: "JKS"
        keystore_path: "/etc/ssl/certs/java/cacerts"
        keystore_pass: "{{ install_apps_ox_post_ox_keystore_passphrase }}"
        state: "present"
      tags:
        - "install_apps_ox_post_cert_system_keystore"

  always:
    - name: "Delete temporary cert directory"
      ansible.builtin.file:
        path: "{{ install_apps_ox_post_cert_temp_dir.path }}"
        state: "absent"
      tags:
        - "cleanup"
  tags:
    - "install_apps_ox_post_cert"
    - "install_apps_ox_post"

- name: "Add master_user user name fix to dovecot (https://dovecot.org/pipermail/dovecot/2019-April/115457.html)"
  ansible.builtin.blockinfile:
    path: "/etc/dovecot/conf.d/90-acl.conf"
    content: "{{ lookup('file', '90-acl.conf') }}"
    state: "present"
    insertbefore: "EOF"
  notify:
    - "Restart dovecot"
    - "Restart OpenXchange"
  tags:
    - "install_apps_ox_post"
    - "install_apps_ox_post_dovecot_acl"

- name: "Toogle OXDrive"
  ansible.builtin.command: >
    udm settings/extended_attribute modify
    --dn "cn=oxDrive,cn=open-xchange,cn=custom attributes,cn=univention,{{ install_apps_ox_post_basedn }}"
    --set default={{ install_apps_ox_post_ox_drive_default }}
  tags:
    - "install_apps_ox_post"
    - "install_apps_ox_post_ox_drive_toggle"

- name: "Force flushing handlers in order to restart dovecot and open-xchange"
  ansible.builtin.meta: "flush_handlers"
  tags:
    - "install_apps_ox_post"
    - "install_apps_ox_post_restart_services"

...
