---

- name: "Converge"
  hosts: "all"
  tasks:
    - name: "Get LDAP base DN from UCR"
      ansible.builtin.command: "ucr get ldap/base"
      register: "ucr_ldap_base"
      changed_when: false
  roles:
    - role: "univention.ucs_roles.ldapsearch_user"
      vars:
        ldapsearch_user_basedn: "{{ ucr_ldap_base.stdout }}"
        ldapsearch_user_list: []
        ldapsearch_user_list_tenantbased: []
