---

- name: "improve_usability_ui_changes | Remove setupSettingsContextMenu from setupMenus()"
  ansible.builtin.lineinfile:
    path: "/usr/share/univention-web/js/umc/hooks/default_menu_entries.js"
    line: "\\s+setupCertificateMenu();"
    state: "absent"
  tags:
    - "improve_usability_ui_changes"
    - "improve_usability_ui_changes_remove_setupsettingscontextmenu"

- name: "improve_usability_ui_changes | Remove setupHelpMenu from setupMenus()"
  ansible.builtin.lineinfile:
    path: "/usr/share/univention-web/js/umc/hooks/default_menu_entries.js"
    line: "\\s+setupHelpMenu();"
    state: "absent"
  tags:
    - "improve_usability_ui_changes"
    - "improve_usability_ui_changes_remove_setuphelpmenu"

- name: "improve_usability_ui_changes | Set username maxLength"
  ansible.builtin.lineinfile:
    path: "/usr/share/univention-management-console-frontend/js/umc/modules/udm/UsernameMaxLengthChecker.js"
    line: "                maxLength: 999,"
    regexp: "maxLength: 20,"
  tags:
    - "improve_usability_ui_changes"
    - "improve_usability_ui_changes_username_max_length"

...
