---
- name: "configure_saml_single_server | Set basic UCR config variables"
  univention.ucs_modules.univention_config_registry:
    keys:
      ucs/server/sso/autoregistraton: "no"
      # yamllint disable-line rule:line-length
      saml/idp/entityID: "https://{{ configure_saml_single_server_external_hostname }}/simplesamlphp/saml2/idp/metadata.php"
      # yamllint disable-line rule:line-length
      saml/idp/certificate/privatekey: "/etc/simplesamlphp/{{ configure_saml_single_server_external_hostname }}-idp-certificate.key"
      # yamllint disable-line rule:line-length
      saml/idp/certificate/certificate: "/etc/simplesamlphp/{{ configure_saml_single_server_external_hostname }}-idp-certificate.crt"
      ucs/server/sso/fqdn: "{{ configure_saml_single_server_external_hostname }}"
      umc/saml/sp-server: "{{ configure_saml_single_server_external_hostname }}"
      ucs/server/sso/virtualhost: "false"
  tags:
    - "configure_saml_single_server"
    - "configure_saml_single_server_run_saml_configuration_script"

- name: "configure_saml_single_server | Create ipmanagedclients for external loadbalancer"
  # yamllint disable rule:line-length
  ansible.builtin.command: >
    udm computers/ipmanagedclient create \
      --position "cn=computers,{{ configure_saml_single_server_basedn }}" \
      --set dnsEntryZoneForward="zoneName={{ configure_saml_single_server_domain_name }},cn=dns,{{ configure_saml_single_server_basedn }}" \
      --set name={{ configure_saml_single_server_domain_prefix|default("portal") }} \
      --set ip={{ configure_saml_single_server_external_loadbalancer_ip }} \
      --set domain={{ configure_saml_single_server_domain_name }} \
      --ignore_exists
  # yamllint enable rule:line-length
  changed_when: "configure_saml_single_server_ipmanagedclients.stdout is search('Object created')"
  failed_when:
    # we are fine when ...
    #   - everything is "ok" (rc == 0)
    #   - we have an error, but we see "[ip] already in use" in either stdout or stderr
    #     (we basically are OK with that specific error)
    - "configure_saml_single_server_ipmanagedclients.rc > 0"
    - "'already in use' not in configure_saml_single_server_ipmanagedclients.stdout"
    - "'already in use' not in configure_saml_single_server_ipmanagedclients.stderr"
  register: "configure_saml_single_server_ipmanagedclients"
  when:
    - "configure_saml_single_server_external_loadbalancer_ip is defined"
    - "configure_saml_single_server_external_loadbalancer_ip|length > 0"
  tags:
    - "configure_saml_single_server"
    - "configure_saml_single_server_ipmanagedclients"

- name: "configure_saml_single_server | Run Univention SAML join script"
  ansible.builtin.command: >
    univention-run-join-scripts --force
    {% if configure_saml_single_server_type == "backup" %}
    -dcaccount "{{ configure_saml_single_admin_user_name }}" -dcpwd "{{ configure_saml_single_temp_file.path }}"
    {% endif %}
    --run-scripts 91univention-saml.inst
  changed_when: false
  tags:
    - "configure_saml_single_server"
    - "configure_saml_single_server_saml_join_script"

- name: "configure_saml_single_server | Restart apache"
  ansible.builtin.service:
    name: "apache2"
    state: "restarted"
  changed_when: false
  tags:
    - "configure_saml_single_server"
    - "configure_saml_single_server_restart_apache"

- name: "configure_saml_single_server | Set UCR idp server variable"
  univention.ucs_modules.univention_config_registry:
    keys:
      # yamllint disable-line rule:line-length
      umc/saml/idp-server: "https://{{ configure_saml_single_server_external_hostname }}/simplesamlphp/saml2/idp/metadata.php"
  failed_when:
    - "configure_saml_single_server_idp_output.rc is defined"
    - "configure_saml_single_server_idp_output.rc > 0"
  register: "configure_saml_single_server_idp_output"
  tags:
    - "configure_saml_single_server"
    - "configure_saml_single_server_idp_ucr_variable"

- name: "configure_saml_single_server | Run Univention management console join script"
  ansible.builtin.command: >
    univention-run-join-scripts --force
    {% if configure_saml_single_server_type == "backup" %}
    -dcaccount "{{ configure_saml_single_admin_user_name }}" -dcpwd "{{ configure_saml_single_temp_file.path }}"
    {% endif %}
    --run-scripts 92univention-management-console-web-server.inst
  changed_when: false
  tags:
    - "configure_saml_single_server"
    - "configure_saml_single_server_management_console_script"

- name: "configure_saml_single_server | Remove default SAML provider"
  ansible.builtin.command:
    argv:
      - "udm"
      - "saml/serviceprovider"
      - "remove"
      - "--dn"
      - "{{ configure_saml_single_server_item }}"
      - "--ignore_not_exists"
  # In force join above, the default provider are added on each run, there a changed will always be deteceted
  # changed_when: "configure_saml_single_server_remove_default_saml_provider_result is not search('Object not found')"
  changed_when: false
  register: "configure_saml_single_server_remove_default_saml_provider_result"
  loop:
    # yamllint disable rule:line-length
    - "SAMLServiceProviderIdentifier=openid-connect-provider,cn=saml-serviceprovider,cn=univention,{{ configure_saml_single_server_basedn }}"
    - "SAMLServiceProviderIdentifier=google.com,cn=saml-serviceprovider,cn=univention,{{ configure_saml_single_server_basedn }}"
    - "SAMLServiceProviderIdentifier=https://sp.testshib.org/shibboleth-sp,cn=saml-serviceprovider,cn=univention,{{ configure_saml_single_server_basedn }}"
    - "SAMLServiceProviderIdentifier=https://saml.salesforce.com,cn=saml-serviceprovider,cn=univention,{{ configure_saml_single_server_basedn }}"
    # yamllint enable rule:line-length
  loop_control:
    loop_var: "configure_saml_single_server_item"
  when:
    - "configure_saml_single_server_basedn is defined"
    - "configure_saml_single_server_basedn|length > 0"
    - "configure_saml_single_server_remove_default_saml_provider is defined"
    - "configure_saml_single_server_remove_default_saml_provider|bool"
  tags:
    - "configure_saml_single_server"
    - "configure_saml_single_server_remove_default_saml_provider"
