---
- name: "Converge"
  hosts: "all"
  tasks:
    - name: "Get LDAP base DN from UCR"
      ansible.builtin.command: "ucr get ldap/base"
      register: "set_dns_glue_record_ucr_ldap_base"
      changed_when: false
    - name: "Get domain name from UCR"
      ansible.builtin.command: "ucr get domainname"
      register: "set_dns_glue_record_ucr_domain_name"
      changed_when: false
  roles:
    - role: "univention.ucs_roles.set_dns_glue_record"
      vars:
        set_dns_glue_record_basedn: "{{ set_dns_glue_record_ucr_ldap_base.stdout }}"
        set_dns_glue_record_domain_name: "{{ set_dns_glue_record_ucr_domain_name.stdout }}"
        set_dns_glue_record_fqdn: "primary.{{ set_dns_glue_record_ucr_domain_name.stdout }}"
        set_dns_glue_record_create_external_hostname_glue_record: false
